name: Docker Linting

runs:
  # compositeが必須
  using: 'composite'
  steps:
    - uses: Kesin11/actions-timeline@v1

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
