name: Daily Build and Push

on:
  schedule:
    - cron: '0 14 * * *' # 毎日UTCの14時に実行

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: "0.0.1"
            aliases: |
              latest
              0
              0.0
          - tag: "main"
            aliases: |
              edge
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout specific tag
        run: git checkout ${{ matrix.tag }}

      - name: Check if the release exists
        if: ${{ matrix.tag }} != 'main'
        id: check_release
        uses: actions/github-script@v6
        with:
          script: |
            const tag = '${{ matrix.tag }}';
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              return true;
            } catch (error) {
              if (error.status === 404) {
                return false;
              } else {
                throw error;
              }
            }

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ vars.DOCKERHUB_REPOSITORY_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=sha-,format=long
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}
            ${{ matrix.aliases }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.tag }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}
            ${{ runner.os }}-buildx-${{ matrix.tag }}
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        if: ${{matrix.tag}} == 'main' || steps.check_release.outputs.result == true
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          sbom: true
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  notify-failed:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: build-and-push
    steps:
      - name: Obtain Repository Name
        id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Notify Failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: danger
          SLACK_TITLE: ":x: [${{ steps.repository.outputs.name }}] Build failed"
          SLACK_MESSAGE: |
            :rotating_light: The build failed for ${{ steps.repository.outputs.name }}.

  notify-success:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: build-and-push
    steps:
      - name: Obtain Repository Name
        id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Notify Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: warning
          SLACK_TITLE: ":tada: [${{ steps.repository.outputs.name }}] Build success"
          SLACK_MESSAGE: |
            :rocket: Daily build for ${{ steps.repository.outputs.name }} has been pushed.
