name: Generate PDF from Markdown with Pandoc Test

on:
  push:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download eisvogel
        run: |
          wget -O eisvogel.tex https://github.com/Wandmalfarbe/pandoc-latex-template/raw/refs/heads/master/eisvogel.tex
      - uses: ./
        with:
          input-file: "README.md"
          output-file: "README.pdf"
          pdf-engine: xelatex
          template: eisvogel.tex
          listings: true
          cjk-mainfont: Noto Serif CJK JP
          mainfont: Noto Serif
          sansfont: Noto Sans
          monofont: Noto Sans Mono CJK JP
          mathfont: Noto Sans Math
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: README.pdf
